name: "AI Code/Paper Reviewer"
description: "AI-powered review bot using Gemini"
branding:
  icon: "book-open"
  color: "purple"

inputs:
  GEMINI_API_KEY:
    description: "Gemini API Key"
    required: false
    default: ""
  GITHUB_TOKEN:
    description: "GitHub Token"
    required: true
  MODEL_CODE:
    description: "Gemini model code"
    default: "models/gemini-2.0-flash"
  LANGUAGE:
    description: "Language for review comments"
    default: "English"
  EXCLUDE_PATHS:
    description: "Comma-separated glob patterns to exclude (e.g. node_modules/**,dist/**)"
    required: false
    default: ""
  REVIEW_MODE:
    description: "ACADEMIC or CODE"
    required: false
    default: "CODE"
  USE_SINGLE_COMMENT_REVIEW:
    description: "true for single summary comment; false for inline comments"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Install dependencies
      shell: bash
      run: cd "${GITHUB_ACTION_PATH}" && npm install

    - name: Run reviewer
      shell: bash
      env:
        GEMINI_API_KEY: ${{ inputs.GEMINI_API_KEY }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

        # 统一 push / pull_request 都存在
        GITHUB_OWNER: ${{ github.repository_owner }}
        GITHUB_REPO: ${{ github.event.repository.name }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        # PR 场景才有值；push 时为空 → dist 中需容错
        GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}

        LANGUAGE: ${{ inputs.LANGUAGE }}
        MODEL_CODE: ${{ inputs.MODEL_CODE }}
        EXCLUDE_PATHS: ${{ inputs.EXCLUDE_PATHS }}
        REVIEW_MODE: ${{ inputs.REVIEW_MODE }}
        USE_SINGLE_COMMENT_REVIEW: ${{ inputs.USE_SINGLE_COMMENT_REVIEW }}
      run: cd "${GITHUB_ACTION_PATH}" && node dist/index.js
